### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by bencen** [liyu001989/lumen-api-demo#11]
// jwt 需要实现的方法
    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    // jwt 需要实现的方法
    public function getJWTCustomClaims()
    {
        return [];
    }

想问下这两个函数主要要实现什么？是否能具体说明？非常感谢。

**Comment by liyu001989** [comment]
这个是 生成jwt token需要用的东西，可以看 vendor/tymon/jwt-auth/src/Contracts/JWTSubject.php

看注释，getJWTIdentifier 是唯一标识，getJWTCustomClaims是一些自定义的参数，一般可能用不到。
我也没仔细研究过jwt，大概应该是这个意思
