### ISSUE TITLE
关于http status 200

### ISSUE THREAD

**Issue by bencen** [liyu001989/lumen-api-demo#13]
今天碰到一个问题，java开发的安卓，只能访问http status200的状态，其他400，500都不解析。晕死。这框架本身很多就是抛出异常，都是400，500的。不知如何解决这种问题。研究了一天，没有头绪。不知能否给出一个解决方案，千分感谢

**Comment by liyu001989** [comment]
当然了，既然是rest风格的，就是基于http，必然要利用http的各种特性，所有的rest应该都是这个样子。这里显然是java的问题，正常的http的库肯定都能拿到head和body，我们两个ios写的app已上架，妥妥的，告诉app开发的同学学习一下http

**Comment by liyu001989** [comment]
请参考github的api   https://developer.github.com/v3/。 201 400 401 403，那github的这些个api都不能用了？

**Comment by bencen** [comment]
你发的这个好像是不存在了。我问过一个人，说是在中间件做处理，但是有一些抛出的异常根本没办法这么做。我只能在跟对方安卓的讨论一下。

**Comment by liyu001989** [comment]
抛出的异常？不是500吗，他就拿到500，显示网络异常啊。你是说他的框架的中间件处理了吗？
https://developer.github.com/v3     最后的句号去掉

**Comment by bencen** [comment]
是的，我问一个群里面的，他是直接在lumen框架中间件处理掉，把那些500，400状态，直接转成200发出，里面多一个如｛'message':'',code:'402'｝这样，但是变成200发出的。

**Comment by liyu001989** [comment]
是可以这样处理，但是既然是rest风格，为什么要这样，app那边肯定能拿到状态吗的，http啊。

**Comment by bencen** [comment]
嗯。我也是这么认为。唉，在跟对方沟通一下。谢谢你。
