### ISSUE TITLE
你最新的升级是做了什么

### ISSUE THREAD

**Issue by bencen** [liyu001989/lumen-api-demo#14]
我看了最近的升级，会不会和之前的版会冲突？更新的东西挺多的。

**Comment by liyu001989** [comment]
写了单元测试，文档啥的，可能会有冲突，但是应该不大

**Comment by liyu001989** [comment]
我感觉你不用跟我的保持一致，我只是个例子，你拿到了肯定要改很多东西，命名空间，api啥的。首先你能正常用了就没问题了，可以重新clone一份，看看单元测试啥的

**Comment by bencen** [comment]
好的，谢谢。
