### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by bencen** [liyu001989/lumen-api-demo#15]
jwt身份验证，框架是否还要加一些别的加密方式，如果私有key之类的。不知这个框架是否支持ssl.每次都在这边打扰你，怪不好意思的。是否可加我qq:121419067

**Comment by liyu001989** [comment]
你说https吗，这个跟框架没啥关系啊。ssl各种库实现就行。看你业务了，我们只是https

**Comment by bencen** [comment]
单单jwt,https，安全吗？是否还需要别的加密方式。比如非对称加密

**Comment by liyu001989** [comment]
我也不是专家，我个人觉得普通的应用足够了，
