### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by 9IPHP** [liyu001989/lumen-api-demo#16]
有个问题想请教下，关于 Token 的刷新机制的。

通过什么方式来刷新 Token 呢？是在请求返回 Token 失效之后去请求刷新一下 Token？然后再请求上次的数据吗？还是过期之前就去刷新？

**Comment by liyu001989** [comment]
首先jwt token的`过期时间`和`刷新时间`都是可以设置的。JWT_TTL，JWT_REFRESH_TTL见config/jwt.php。比如说token 60秒就过期，但是在未来的一天内都可以refresh 这个token

1. 基本的就是客户端发现过期了，尝试刷新token，成功了继续请求原有数据，不成功就重新登录。基本上这样就满足了。
2. 或者客户端每次请求token 的同时让服务端把`过期时间`返回，存下来，客户端去判断什么时候该刷新。那可能这样的话，服务端可以把`刷新时间`也返回来，如果token过了刷新时间则直接让用户登录。

我们用的1，感觉即便按2这样做，如果token有什么黑名单啊，强制过期啊之类的功能，一样会返回401，一样会重复1的步骤，所以1是必须的。

**Comment by 9IPHP** [comment]
好的，多谢~
