### ISSUE TITLE
请问Transformer里面的includeUser怎样使用啊？

### ISSUE THREAD

**Issue by Tang1024** [liyu001989/lumen-api-demo#18]
我现在是这样子手动加载使用。我看见你的demo里面没有其他关于includeUser调用的代码。自己尝试了很久也没发现可以自动加载的。
```php
return $this->response()
            ->paginator($articles, (new ArticleTransformer)->setDefaultIncludes(['user']));
```

**Comment by liyu001989** [comment]
这个是客户端通过url决定的。

比如
1. 客户端只想得到 post 数据
http://xxxxxx/api/posts

2. 客户端想得到 post 数据的同时得到 user 数据
http://xxxxxx/api/posts?include=user

当第二种情况的时候会自动去调用 postTransformer 里面的 includeUser。
当然你也可以再postTransformer 里面设置 user 为 defaultInclude，这样 http://xxxxxx/api/posts 这么请求也会有 user 数据

我不知道我解释清楚没

**Comment by Tang1024** [comment]
@liyu001989 那就是我不需要其他任何设置了，只需要在请求的地址添加include参数就可以自动调用了？

**Comment by liyu001989** [comment]
是的，但是需要在 transformer 里面定义 protected $availableIncludes = ['user', 'xxx'];  可以被include的参数，这样会调用 includeUser 和 includeXxx 方法。

[例子](https://github.com/liyu001989/lumen-api-demo/blob/master/app/ApiDemo/Transformers/PostTransformer.php)
