### ISSUE TITLE
Using Session inside Lumen

### ISSUE THREAD

**Issue by anhphamt** [liyu001989/lumen-api-demo#19]
First thing, thank you to create this very useful demo API in Lumen. 

I have a question related to work around using PHP session in Lumen 5.2 and 5.3. I know it's removed in these version. Just wonder if you have any advice if I want to use Session.

Again thank you very much

**Comment by liyu001989** [comment]
First, why you want to use session ?

You can use cache and jwt instead of session.

**Comment by anhphamt** [comment]
I tried to integrate SocialLogin to Lumen and use the old way (stick with session)
Now I found that SocialLite can work with Lumen and stateless. 

In general, if I need session way, I will try to use cache and jwt. 

Thank you for your answer.
