### ISSUE TITLE
项目没部署成功

### ISSUE THREAD

**Issue by jnuc093** [liyu001989/lumen-api-demo#2]
➜  ~ homestead edit
    - map: h.lumen-api-demo
      to: /home/vagrant/Code/lumen-api-demo/public

/etc/hosts:

      127.0.0.1 h.luemn-api-demo

vagrant halt
vagrant up -provision

➜  ~ curl http://h.lumen-api-demo:8000/api/auth/signin
curl: (6) Could not resolve host: h.lumen-api-demo

**Comment by liyu001989** [comment]
你是使用homestead，那么homestead的ip地址应该是Homestead.yaml 的ip:xxx.xxx.xxx.xx
所以你的host应该是 xxx.xxx.xxx.xx h.luemn-api-demo

这个显然是环境问题啊

**Comment by jnuc093** [comment]
嗯。环境问题。谢谢，我再找找。
