### ISSUE TITLE
请问能使用模糊查询吗

### ISSUE THREAD

**Issue by erroristyun** [liyu001989/lumen-api-demo#22]
请问能使用模糊查询吗，where(array $data)->paginate();  这样只能正确匹配，我想进行模糊匹配的，像like %abd%

**Comment by liyu001989** [comment]
where([['foo','like','%abd%']])->paginate();
repository 我只是简单的实现了一下，其实就是调用model。
你可以自己修改，也可以试试别的库

**Comment by erroristyun** [comment]
where([['foo','like','%abd%']])->paginate(); 这样还是没成功

**Comment by liyu001989** [comment]
<img width="551" alt="2016-11-23 7 01 50" src="https://cloud.githubusercontent.com/assets/2981799/20559431/54ab2cbc-b1af-11e6-9795-a46cbeb2005e.png">
<img width="996" alt="2016-11-23 7 02 22" src="https://cloud.githubusercontent.com/assets/2981799/20559441/6518142a-b1af-11e6-8c35-d4a3108fb81a.png">

或者你可以不用仓库  直接用orm做查询吧

**Comment by erroristyun** [comment]
哦哦，谢谢啦，你人真好，写的demo也很好，果断路转粉啊

**Comment by liyu001989** [comment]
😄 👍
