### ISSUE TITLE
put接收不到数据

### ISSUE THREAD

**Issue by 472643931** [liyu001989/lumen-api-demo#23]
我在做update操作的时候接受不都put/patch过来的数据，get,post,delete都行。不知道是不是dingo哪里没有配置好。lumen 5.3

**Comment by liyu001989** [comment]
你是使用postman调试的吗，可能是这个问题，put和patch需要使用x-www-form-urlencoded
<img width="408" alt="2016-12-14 11 13 45" src="https://cloud.githubusercontent.com/assets/2981799/21168377/72c67676-c1ee-11e6-84d3-2408050b52ef.png">

**Comment by 472643931** [comment]
@liyu001989 是的我用的postman，多谢啊
