### ISSUE TITLE
wrong assignment in base repo

### ISSUE THREAD

**Issue by xuzc** [liyu001989/lumen-api-demo#25]
file: app/Repositories/Eloquent/BaseRepository.php

```
public function where(array $data)
{
    $this->model = $this->model->where($data);
    return $this;
}
```

$model->where() will call the magic method __call, and get the new instance of '\Illuminate\Database\Eloquent\Builder' rather than the '\Illuminate\Database\Eloquent\Model'

**Comment by liyu001989** [comment]
[rinvex/repository](https://github.com/rinvex/repository) 

There is a better implement about repository you can try.

 I have no better idea about `$repository->where()->where()->find()`.

**Comment by liyu001989** [comment]
commit 04f9eb2a782ef1fbc211d445ba2700f7af9c9339
Author: Yu Li <liyu001989@gmail.com>
Date:   Mon Jan 16 23:56:46 2017 +0800

    use rinvex/repository
