### ISSUE TITLE
http://lumen.com/api/users

### ISSUE THREAD

**Issue by zengyuanye** [liyu001989/lumen-api-demo#29]
No input file specified.
http://lumen.com这个是本地nginx重定向与app，public等同级目录
还有就是apidoc文件无法打开

**Comment by liyu001989** [comment]
首先这是nginx 配置的问题，找找网上正确的配置吧
apidoc 打不开，可能某些样式，字体被墙了？具体参考 apidoc吧，或者你自己生成一下试试
是在不行，直接看代码上面的注释吧

**Comment by liyu001989** [comment]
再试试吧，有部分样式忘了提交了，pull一下应该好了
http://lumen.lyyw.info/apidoc   这个应该也好了

**Comment by zengyuanye** [comment]
好的
问题解决了：http://lumen.com域名必须是public目录下lumen-api-demo/public
