### ISSUE TITLE
关于usage步骤 配置各种key的一些讨论

### ISSUE THREAD

**Issue by jnuc093** [liyu001989/lumen-api-demo#3]
➜  lumen-api-demo git:(master) ✗ php artisan key:generate
	Application key [eFoEZeANciqkaM8YdoTeKXN9dKRUoXsN] set successfully.
	➜  lumen-api-demo git:(master) ✗ php artisan jwt:generate

  	[Symfony\Component\Console\Exception\CommandNotFoundException]
	  Command "jwt:generate" is not defined.
  	Did you mean one of these?
      key:generate
      jwt:secret

	➜  lumen-api-demo git:(master) ✗ php artisan key:generate
	Application key [olwMeLDwDuQ9eKKoIZ7RWZmXm2WMDPuo] set successfully.

以上生成的key需要手动拷贝到 .env里面，好像laravel5.1是自动跟新该文件的。另外要使以上命令能运行需要按照以下的步骤设置一下。	
[Lumen Micro Framework => php artisan key:generate](http://stackoverflow.com/questions/30344141/lumen-micro-framework-php-artisan-keygenerate)

**Comment by liyu001989** [comment]
这两个key就是随机字符串
随便找个地方生成了，配置一下吧，也就配置这么一次
echo md5(uniqid()) ,  str_random(32);  都挺方便的
