### ISSUE TITLE
need authentication的情况下，发送带有token的header，会返回The Response content must be a string or object implementing __toString(), \"boolean\" given.

### ISSUE THREAD

**Issue by yumanchao** [liyu001989/lumen-api-demo#30]
在本地调试的，不知道怎么回事，重新下载最新版，全新安装的也是这种情况   php version 5.6.27  + apache 我测试了https://lumen.lyyw.info/api/user 没有返回这个错误，请帮助看下，多谢
流程：
1.通过https://lumen.lyyw.info/api/users，post用户，得到token
2.通过https://lumen.lyyw.info/api/user header里面Authorization为：Bearer {token}
流程应该是没有问题的，用的postman调试的

**Comment by yumanchao** [comment]
经过调试发现 $this->user() 为 NULL

**Comment by yumanchao** [comment]
经过调试发现返回的是一个 false

**Comment by liyu001989** [comment]
没有重现你的问题，我本地是好的，线上demo是好的，基本上是你web服务器的问题。
你可以  php -S localhost:8000 -t public   确认一下

**Comment by yumanchao** [comment]
多谢，我再调试下看看

**Comment by yumanchao** [comment]
配置文件中的CACHE_DRIVER=redis  SESSION_DRIVER=redis 改为file 就可以了 本地没有redis
