### ISSUE TITLE
想请教一下使用JWT的时候token这部分怎么自己定义呢？

### ISSUE THREAD

**Issue by wangxiaojun111** [liyu001989/lumen-api-demo#34]
![image](https://user-images.githubusercontent.com/13449944/26923294-4082698e-4c74-11e7-9ef0-bcc7eac0ee2e.png)

**Comment by liyu001989** [comment]
你是需要额外的参数？

`tymon/jwt-auth` 这个库默认就是加密个id，传过来，decode，然后根据id查找用户。需要额外信息可以使用 getJWTCustomClaims

**Comment by wangxiaojun111** [comment]
对就是要额外加几个参数，您有相关的文档吗？

**Comment by liyu001989** [comment]
![image](https://user-images.githubusercontent.com/2981799/26923648-4adeec44-4c75-11e7-93c1-c4ee1039cfca.png)
```
$payload = \Auth::getPayload();
$payload->get('type');
```

具体你得看你使用的package 的文档。

**Comment by wangxiaojun111** [comment]
👌  谢谢了 终于有头绪了
