### ISSUE TITLE
请教一个关于dingo api的问题

### ISSUE THREAD

**Issue by huantu284** [liyu001989/lumen-api-demo#38]
您好，请问如何能统一dingo api返回的异常处理结构，现在一旦报异常，就只有messaage和status_code2个字段；比如我用laravel5.4的用户授权中，采用Policy方式，在路由中加can:update,**，来验证授权，一旦授权不允许，会返回
`
{
    "message": "This action is unauthorized.",
    "status_code": 500
}
`

我想自定义这个结构。

**Comment by liyu001989** [comment]
https://github.com/liyu001989/dingo-api-wiki-zh/blob/master/Errors-And-Error-Responses.md 
这里有将如何自定义异常的响应。不知道你的自定义是啥意思

**Comment by huantu284** [comment]
您这篇翻译我也看了，我再路由里加了
app('Dingo\Api\Exception\Handler')->register(function (\Illuminate\Auth\Access\AuthorizationException $exception) {
    return Response::make(['error' => '权限错误'], 401);
});

确实生效了，但是我想知道这个register放哪更合适；

**Comment by liyu001989** [comment]
放在某个 provider 就行

**Comment by huantu284** [comment]
不好意思一直麻烦您，
问题1：https://github.com/liyu001989/dingo-api-wiki-zh/blob/master/Errors-And-Error-Responses.md
这里的异常，我想统一增加一个result字段，内容为failure，请问有没有统一修改返回结构的方法。
问题2：如果是未知结构异常，请问怎么自定义通用的响应内容。

**Comment by liyu001989** [comment]
问题1可以试试这个
```
$app['Dingo\Api\Exception\Handler']->setErrorFormat([
    'error' => [
        'message' => ':message',
        'errors' => ':errors',
        'code' => ':code',
        'status_code' => ':status_code',
        'debug' => ':debug'
    ]
]);
```

问题2，设置了问题已应该所有的都变了，但是为什么要做这么多自定义的事情

**Comment by huantu284** [comment]
对，如您所说，这么设置之后，所有的就都可以改变了，主要是返回信息，我想搞成中文的

**Comment by liyu001989** [comment]
默认只是显示异常里面的message而已，要么一个一个注册然后显示成中文，要么在返回的时候，想办法翻译一下。
```
         $this->app->singleton('api.exception', function ($app) {
             return new ExceptionHandler($app['Illuminate\Contracts\Debug\ExceptionHandler'], $this->config('errorFormat'), $this->config('debug'));
         });
```
比如替换为一个自己的ExceptionHandler，想办法翻译。

我觉得英文挺好，客户端可以判断状态码，显示个统一的中文提示就行，比如401 未登录，403 未授权500 服务器异常   之类的。

**Comment by huantu284** [comment]
好的，我的问题都解决了，谢谢您，一直骚扰您真的不好意思。
