### ISSUE TITLE
接口是使用policy ,报错  “This action is unauthorized”

### ISSUE THREAD

**Issue by cmming** [liyu001989/lumen-api-demo#41]
//policy中修改资源的权限  UserOriResPolicy
	public function update(User $user,UserOriFiles $userOriFiles){
		return $user->uid === $userOriFiles->author_id;
	}

// controller中的方法
public function update($id){
		//侧路模式的权限判断

		$userOriFile = UserOriFiles::find($id);
		$isok = $this->authorize('update',$userOriFile);

最后接口一直报错
“This action is unauthorized”，
google 上有这个问题，但没有回答，你有在项目中用到Policy 吗？

https://www.laracasts.com/discuss/channels/laravel/laravel-54-policies-not-working-with-jwt

**Comment by liyu001989** [comment]
那你就在policy里面日志一下，看看为什么$user->uid === $userOriFiles->author_id  是false啊。跟jwt有什么关系，用户你都拿到了。我在项目中用，没有问题

**Comment by cmming** [comment]
改了一下，注册策略的模式，就好了
//		'\App\Models\UserOriFiles' =>'\App\Policies\UserOriResPolicy'
		\App\Models\UserOriFiles::class =>\App\Policies\UserOriResPolicy::class（改成这样就好了）
