### ISSUE TITLE
meta

### ISSUE THREAD

**Issue by yangzuwei** [liyu001989/lumen-api-demo#44]
meta中的links格式问题，如果links为空，返回一个空数组，反之返回一个对象，这种数据不一致的情况算bug吗？具体源码出在这里\vendor\league\fractal\src\Serializer\ArraySerializer.php，        $pagination['links'] = [];

        if ($currentPage > 1) {
            $pagination['links']['previous'] = $paginator->getUrl($currentPage - 1);
        }

        if ($currentPage < $lastPage) {
            $pagination['links']['next'] = $paginator->getUrl($currentPage + 1);
        }

这里如果 $pagination['links'] 没有值的情况下，直接就输入出了初始化的这个[]

**Comment by liyu001989** [comment]
为什么算bug 啊，没有link就是没有资源相关的其他链接了。不然应该返回啥呢

**Comment by yangzuwei** [comment]
客户端这边反应的，他们认为links这里如果是统一是一个“对象”就是应该给对象格式，而不是数组格式

**Comment by yangzuwei** [comment]
"meta": {
        "pagination": {
            "total": 11,
            "count": 11,
            "per_page": 20,
            "current_page": 1,
            "total_pages": 1,
            "links": []
        }
    }
以上这种应该要换成这种
    "meta": {
        "pagination": {
            "total": 11,
            "count": 11,
            "per_page": 20,
            "current_page": 1,
            "total_pages": 1,
            "links": {}
        }
    }
才是格式统一的

**Comment by liyu001989** [comment]
凭什么 links 必须是个对象，给出合理的解释，统一返回数组怎么了

**Comment by yangzuwei** [comment]
links空值的时候是以上那样的，如果是非空值的时候张这样：

    "meta": {
        "pagination": {
            "total": 11,
            "count": 2,
            "per_page": 2,
            "current_page": 2,
            "total_pages": 6,
            "links": {
                "previous": "http://api.com/api/users?page=1",
                "next": "http://api.com/api/users?page=3"
            }
        }
    }

这里links是一个对象，格式不统一，对于客户端而言，这里解析的时候，要判断links的类型

**Comment by liyu001989** [comment]
因为有值得时候是对象，抱歉才看明白，那么我觉得没值得时候返回  "links": null 比较好，空对象不是很奇怪吗。我看看代码怎么改

**Comment by yangzuwei** [comment]
我认为是php语法糖的原因，大家都喜欢数组太习惯了，这里本身严格来说应该是对象定义的，我自己这里私下加了一句，       

 if(empty($pagination['links'])){
            $pagination['links'] = new \stdClass();
        }

我觉得是{}比null好，在w3c里面给出的json说明中是这样描述的
数据在名称/值对中
数据由逗号分隔
花括号保存对象
方括号保存数组

**Comment by liyu001989** [comment]
你可以参考  https://github.com/liyu001989/dingo-serializer-switch/tree/master   我这个项目的做法，自己修改一下serializer。null理解起来很通顺，我改成null了。你按照自己的理解修改。

友情提示，不要直接修改vendor中的文件，不要提交vendor到版本库

**Comment by yangzuwei** [comment]
好的，多谢，vendor中的东西我生产环境中不会去动的，这里暂时只是做实验。你的restful理解那篇文章写得很好，我安利给现在项目组的同事了，感谢分享。
