### ISSUE TITLE
安装好了，但是报一个错。

### ISSUE THREAD

**Issue by bencen** [liyu001989/lumen-api-demo#8]
http://lumen.jmqu.cn/auth/register
post
email:2@xxx.c.com
password:xxxx
{
  "message": "Declaration of ApiDemo\\Repositories\\Eloquent\\BaseRepository::update() must be compatible with ApiDemo\\Repositories\\Contracts\\RepositoryInterface::update(ApiDemo\\Repositories\\Contracts\\int $id, array $attributes)",
  "code": 64,
  "status_code": 500
}
报这个错是什么原因？

**Comment by liyu001989** [comment]
我这是好的，稍等我研究一下

**Comment by bencen** [comment]
好的，谢谢，我这个是内网地址。
我有设置.evn.里面设置了数据库。其他都没有设置了。
我说下我的步骤
1.下载你的包
2.cd 目录
3.composer install
4.cp .env.example .env
5.设置mysql数据库，把API_PREFIX注了用API_DOMAIN，app_key设置了一个32位
6.php artisan jwt:secret 
7.php artisan migrate
8.然后用postman提交了上面的数据。就报这个错了。不知道我是少设置了什么。

**Comment by liyu001989** [comment]
你php是什么版本

**Comment by bencen** [comment]
PHP Version 5.5.30

**Comment by liyu001989** [comment]
http://php.net/manual/zh/functions.arguments.php    
php 版本的问题   
我也才知道php7 才支持  int 类型限定

**Comment by liyu001989** [comment]
repository  我自己随便写了些   封装的不好
你可以看看rinvex/repository  或者 prettus/l5-repository  这两个包

**Comment by bencen** [comment]
好的。谢谢。

**Comment by bencen** [comment]
你这个版是支持Php7?

**Comment by bencen** [comment]
我改掉就可以了，谢谢。
